<?php
/**
 * Web installer (/setup). One form: database, site name, administrator.
 * Writes data/config.php only after the schema and seed data were created successfully.
 */
function setup_index(): never
{
    if (is_installed() && setting('installed_at', '') !== '') redirect(url('/'));
    $checks = setup_checks();
    $errors = [];
    $values = ['driver' => extension_loaded('pdo_mysql') ? 'mysql' : 'sqlite', 'mysql_host' => '127.0.0.1', 'mysql_port' => '3306', 'mysql_name' => '', 'mysql_user' => '', 'mysql_pass' => '', 'site_name' => 'My Forum', 'lang' => 'en', 'admin_name' => 'admin', 'admin_email' => '', 'admin_pass' => ''];
    if (is_post()) {
        foreach ($values as $k => $v) $values[$k] = post_str($k, 500);
        $values['mysql_pass'] = post_secret('mysql_pass');
        $values['admin_pass'] = post_secret('admin_pass');
        foreach ($checks as $c) if ($c['fatal'] && !$c['ok']) $errors[] = $c['label'] . ': ' . $c['detail'];
        if (!username_valid($values['admin_name'])) $errors[] = t('Administrator username must be 2-30 characters: letters, numbers, dot, dash or underscore.');
        if (strlen($values['admin_pass']) < 8) $errors[] = t('Administrator password must be at least 8 characters.');
        if ($values['admin_email'] !== '' && !filter_var($values['admin_email'], FILTER_VALIDATE_EMAIL)) $errors[] = t('Please enter a valid email address.');
        if ($values['site_name'] === '') $values['site_name'] = 'My Forum';
        if (!isset(lang_available()[$values['lang']])) $values['lang'] = 'en';
        $db = $values['driver'] === 'mysql'
            ? ['driver' => 'mysql', 'host' => $values['mysql_host'], 'port' => (int)$values['mysql_port'], 'name' => $values['mysql_name'], 'user' => $values['mysql_user'], 'pass' => $values['mysql_pass']]
            : ['driver' => 'sqlite', 'path' => DATA_DIR . '/flatbb-' . random_token(6) . '.sqlite']; // random name: unguessable even if data/ is exposed
        if ($errors === []) {
            try {
                db_connect($db)->query('SELECT 1');
            } catch (Throwable $e) {
                $errors[] = t('Database connection failed: %s', $e->getMessage());
            }
        }
        if ($errors === []) {
            $config = ['db' => $db, 'secret' => random_token(32), 'debug' => false, 'lang' => $values['lang']];
            config(null, null, $config);
            try {
                schema_install();
                if (val('SELECT COUNT(*) FROM fb_users') == 0) {
                    schema_seed($values['admin_name'], $values['admin_email'], $values['admin_pass']);
                } else {
                    save_settings(['installed_at' => (string)now()]);
                }
                save_settings(['site_name' => $values['site_name'], 'site_lang' => $values['lang'] === 'en' ? '' : $values['lang'], 'rewrite' => setup_rewrite_works() ? '1' : '0']);
                $php = "<?php\n// flatbb configuration. Generated by the installer on " . date('Y-m-d') . ".\nreturn " . var_export($config, true) . ";\n";
                if (@file_put_contents(CONFIG_FILE, $php, LOCK_EX) === false) throw new RuntimeException('Cannot write data/config.php');
                @file_put_contents(DATA_DIR . '/.htaccess', "Require all denied\n");
                @file_put_contents(DATA_DIR . '/index.html', '');
                $admin = user_by_name($values['admin_name']);
                if ($admin !== null) login_user($admin);
                flash(t('flatbb is installed. Welcome!'));
                redirect(url('/'));
            } catch (Throwable $e) {
                $errors[] = t('Installation failed: %s', $e->getMessage());
            }
        }
    }
    header('Content-Type: text/html; charset=utf-8');
    echo view('setup', ['checks' => $checks, 'errors' => $errors, 'values' => $values]);
    exit;
}

function setup_checks(): array
{
    $writable = static fn(string $dir): bool => (is_dir($dir) || @mkdir($dir, 0755, true)) && is_writable($dir);
    return [
        ['label' => 'PHP >= 8.1', 'ok' => PHP_VERSION_ID >= 80100, 'detail' => PHP_VERSION, 'fatal' => true],
        ['label' => 'PDO SQLite', 'ok' => extension_loaded('pdo_sqlite'), 'detail' => extension_loaded('pdo_sqlite') ? 'available' : 'missing (required for SQLite)', 'fatal' => false],
        ['label' => 'PDO MySQL', 'ok' => extension_loaded('pdo_mysql'), 'detail' => extension_loaded('pdo_mysql') ? 'available' : 'missing (required for MySQL)', 'fatal' => false],
        ['label' => 'mbstring', 'ok' => extension_loaded('mbstring'), 'detail' => extension_loaded('mbstring') ? 'available' : 'missing', 'fatal' => true],
        ['label' => 'GD (images)', 'ok' => function_exists('imagecreatetruecolor'), 'detail' => function_exists('imagecreatetruecolor') ? 'available' : 'missing: avatars and image resizing disabled', 'fatal' => false],
        ['label' => 'data/ writable', 'ok' => $writable(DATA_DIR), 'detail' => DATA_DIR, 'fatal' => true],
        ['label' => 'data/cache/ writable', 'ok' => $writable(CACHE_DIR), 'detail' => CACHE_DIR, 'fatal' => true],
        ['label' => 'uploads/ writable', 'ok' => $writable(UPLOAD_DIR), 'detail' => UPLOAD_DIR, 'fatal' => false],
    ];
}

/** Probe /__rewrite_check on this host; true when clean URLs work. */
function setup_rewrite_works(): bool
{
    $url = base_url() . '/__rewrite_check';
    $r = false;
    if (function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt_array($ch, [CURLOPT_RETURNTRANSFER => true, CURLOPT_TIMEOUT => 4, CURLOPT_CONNECTTIMEOUT => 3, CURLOPT_SSL_VERIFYPEER => false, CURLOPT_SSL_VERIFYHOST => 0, CURLOPT_FOLLOWLOCATION => false, CURLOPT_USERAGENT => 'flatbb-installer']);
        $r = curl_exec($ch);
        curl_close($ch);
    }
    if ($r === false && ini_get('allow_url_fopen')) {
        $ctx = stream_context_create(['http' => ['timeout' => 3, 'ignore_errors' => true, 'user_agent' => 'flatbb-installer'], 'ssl' => ['verify_peer' => false, 'verify_peer_name' => false]]);
        $r = @file_get_contents($url, false, $ctx);
    }
    return is_string($r) && trim($r) === 'ok';
}
